version: 2.1

orbs:
  hokusai: artsy/hokusai@dev:7140b0e073a71f7f54959c178c0caec5

not_staging_or_release: &not_staging_or_release
  filters:
    branches:
      ignore:
        - staging
        - release

only_master: &only_master
  context: hokusai
  filters:
    branches:
      only: master

only_release: &only_release
  context: hokusai
  filters:
    branches:
      only: release

workflows:
  default:
    jobs:
      # pre-staging
      - hokusai/test:
          name: test
          executor: beta
          filename: ./hokusai/test.yml.j2
          <<: *not_staging_or_release

      # staging
      - hokusai/push:
          name: push-staging-image
          executor: beta
          <<: *only_master
          requires:
            - test

      - hokusai/deploy-staging:
          <<: *only_master
          executor: beta
          project-name: hokusai-sandbox
          requires:
            - push-staging-image

      # release
      - hokusai/deploy-production:
          executor: beta
          <<: *only_release
