version: 2.1

orbs:
  hokusai: artsy/hokusai@volatile
  artsy-remote-docker: artsy/remote-docker@volatile

not_staging_or_release: &not_staging_or_release
  filters:
    branches:
      ignore:
        - staging
        - release

only_main: &only_main
  context: hokusai
  filters:
    branches:
      only: main

only_release: &only_release
  context: hokusai
  filters:
    branches:
      only: release

workflows:
  default:
    jobs:

      - hokusai/test:
          name: build-and-test
          executor: hokusai/beta
          filename: ./hokusai/test.yml.j2
          <<: *not_staging_or_release

      - hokusai/push:
          name: push-staging-image
          executor: hokusai/beta
          <<: *only_main
          requires:
            - build-and-test

      - artsy-remote-docker/build:
          <<: *not_staging_or_release
          context: hokusai
          executor: hokusai/beta
          name: remote-build

      - artsy-remote-docker/test:
          context: hokusai
          executor: hokusai/beta
          name: test-remote-build
          <<: *not_staging_or_release
          requires:
            - remote-build

      - hokusai/deploy-staging:
          <<: *only_main
          executor: hokusai/beta
          project-name: hokusai-sandbox
          requires:
            - build-and-test
            - test-remote-build
          name: deploy-staging

      # release
      - hokusai/deploy-production:
          executor: hokusai/beta
          <<: *only_release
