version: 2
jobs:
  test:
    docker:
      - image: artsy/hokusai:head
    steps:
      - add_ssh_keys
      - checkout
      - setup_remote_docker
      - run:
          name: Test
          command: hokusai test
  push:
    docker:
      - image: artsy/hokusai:head
    steps:
      - add_ssh_keys
      - checkout
      - setup_remote_docker
      - run:
          name: Push
          command: hokusai registry push --tag $CIRCLE_SHA1 --force --overwrite
  deploy:
    docker:
      - image: artsy/hokusai:head
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: Configure
          command: hokusai configure --kubectl-version 1.10.7 --s3-bucket artsy-citadel --s3-key k8s/config --platform linux
      - run:
          name: Deploy
          command: hokusai staging update --skip-checks --dry-run
      - run:
          name: Deploy
          command: hokusai staging deploy $CIRCLE_SHA1 --update-config
      - run:
          name: Update Staging branch
          command: git push git@github.com:artsy/hokusai-sandbox.git $CIRCLE_SHA1:refs/heads/staging --force
workflows:
  version: 2
  default:
    jobs:
      - test
      - push:
          context: hokusai
          filters:
            branches:
              only: master
          requires:
            - test
      - deploy:
          context: hokusai
          filters:
            branches:
              only: master
          requires:
            - push
