version: 2.1

orbs:
  hokusai: artsy/hokusai@dev:7140b0e073a71f7f54959c178c0caec5
  artsy-remote-docker: artsy/remote-docker@dev:7140b0e073a71f7f54959c178c0caec5

jobs:
  test:
    docker:
      - image: artsy/hokusai:0.5.10
    steps:
      - add_ssh_keys
      - checkout
      - setup_remote_docker
      - run: hokusai registry pull --tag "$CIRCLE_SHA1"
      - run:
          name: Test
          command: hokusai test --no-build
          no_output_timeout: 3600s

not_staging_or_release: &not_staging_or_release
  filters:
    branches:
      ignore:
        - staging
        - release

only_master: &only_master
  context: hokusai
  filters:
    branches:
      only: master

only_release: &only_release
  context: hokusai
  filters:
    branches:
      only: release

workflows:
  default:
    jobs:
      # pre-staging
      - artsy-remote-docker/build:
          <<: *not_staging_or_release
          context: hokusai
          name: build

      - test:
          <<: *not_staging_or_release

      # staging
      - hokusai/push:
          name: push-staging-image
          executor: hokusai/beta
          <<: *only_master
          requires:
            - test

      - hokusai/deploy-staging:
          <<: *only_master
          executor: hokusai/beta
          project-name: hokusai-sandbox
          requires:
            - push-staging-image

      # release
      - hokusai/deploy-production:
          executor: hokusai/beta
          <<: *only_release
