---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ project_name }}-cron
spec:
  schedule: 23 10 * * MON
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ project_name }}-cron
            args:
            - bar
