---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hokusai-sandbox-cron
spec:
  schedule: 23 09 * * MON
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hokusai-sandbox-cron
            image: foo-ecr-repo:production
            imagePullPolicy: Always
            envFrom:
            - configMapRef:
                name: hokusai-sandbox-environment
            args:
            - hostname
          restartPolicy: Never
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: tier
                    operator: In
                    values:
                    - background
