---
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: version-label
labels:
  app.kubernetes.io/version: staging
fieldSpecs:
- path: metadata/labels
  kind: Deployment
- path: spec/template/metadata/labels
  kind: Deployment
