---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hokusai-sandbox-web
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hokusai-sandbox
      component: web
      layer: application
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hokusai-sandbox
        component: web
        layer: application
      name: hokusai-sandbox-web
    spec:
      containers:
        - name: hokusai-sandbox-web
          envFrom:
            - configMapRef:
                name: hokusai-sandbox-environment
          image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/hokusai-sandbox:production
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hokusai-sandbox
    component: web
    layer: application
  name: hokusai-sandbox-web
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: hokusai-sandbox
    component: web
    layer: application
  type: ClusterIP
