---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hokusai-sandbox-web-canary
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hokusai-sandbox-canary
      component: web
      layer: application
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hokusai-sandbox-canary
        component: web
        layer: application
      name: hokusai-sandbox-web-canary
    spec:
      containers:
      - env:
          - name: PORT
            value: "3000"
        envFrom:
        - configMapRef:
            name: hokusai-sandbox-environment
        image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/hokusai-sandbox:staging
        imagePullPolicy: Always
        name: hokusai-sandbox-web
        ports:
        - name: http
          containerPort: 3000
