# prettier-ignore

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ project_name }}-web-canary
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ project_name }}-canary
      component: web
      layer: application
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ project_name }}-canary
        component: web
        layer: application
      name: {{ project_name }}-web-canary
    spec:
      containers:
      - env:
          - name: PORT
            value: "3000"
        envFrom:
        - configMapRef:
            name: {{ project_name }}-environment
        image: {{ project_repo }}:staging
        imagePullPolicy: Always
        name: {{ project_name }}-web
        ports:
        - name: http
          containerPort: 3000
