---
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: app-label
labels:
  app: hokusai-sandbox
fieldSpecs:
- path: metadata/labels
- path: spec/selector/matchLabels
  kind: Deployment
- path: spec/template/metadata/labels
  kind: Deployment
- path: spec/selector
  kind: Service
---
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: version-label
labels:
  app.kubernetes.io/version: production
fieldSpecs:
- path: metadata/labels
  kind: Deployment
- path: spec/template/metadata/labels
  kind: Deployment
